
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aiveyvvhlfiqhbaqazrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpdmV5dnZobGZpcWhiYXFhenJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzAyNTcsImV4cCI6MjA2NjAwNjI1N30.FkZA2BnrPVNJ-Ly3oAjqC-AnsqTpX9agiCP5Xjg_nQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
